env:
  global:
  - CC_TEST_REPORTER_ID=7dd0be3f5f3bc2c79e3e65f5925b7c45fbf7269751d6f5259a87bc5d44f686e1
language: ruby
sudo: true
services:
- redis-server
before_script:
- bundle exec rake db:migrate RAILS_ENV=test
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64
  > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script: CODECLIMATE_REPO_TOKEN=7dd0be3f5f3bc2c79e3e65f5925b7c45fbf7269751d6f5259a87bc5d44f686e1
  bundle exec rake
after_script: "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi"
before_install:
- openssl aes-256-cbc -K $encrypted_7f851eb87e48_key -iv $encrypted_7f851eb87e48_iv
  -in .deploy-client-credentials.tar.gz.enc -out .deploy-client-credentials.tar.gz
  -d
- tar -xzf .deploy-client-credentials.tar.gz
- export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
- echo "deb http://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee
  -a /etc/apt/sources.list.d/google-cloud-sdk.list
- curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
- sudo apt-get update && sudo apt-get install google-cloud-sdk
- gcloud version
- gcloud auth activate-service-account --key-file gae-client-secret.json --quiet
- gcloud config set project xyz-api --quiet
- mkdir tmp
- mkdir tmp/pids
- mkdir log
- touch tmp/pids/sidekiq.pid
- touch log/sidekiq.log
install:
- gem install rubygems-update
- update_rubygems
- sudo apt-get install imagemagick
- gem update --system
- bundle install
deploy:
  skip_cleanup: true
  on: master
  provider: script
  script: gcloud app deploy app.yaml worker.yaml --quiet
addons:
  code_climate:
    repo_token: 7dd0be3f5f3bc2c79e3e65f5925b7c45fbf7269751d6f5259a87bc5d44f686e1
